### ISSUE TITLE
Consider adding more intelligence

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-TypingBreaks#6]
If it's practical, I think this plugin could be much better by adding a little bit of intelligence and making the definition of a "break" more flexible. For example, suppose I had `idle_time_limit` set to 5 minutes, but I wanted a few isolated keypresses to not trigger that timer to reset. It would be considerably more logic to do something like this, but it seems obvious that a period of 5 minutes in which only one key was pressed was a break from typing that should probably be counted as such.

I'm guessing that the simplest version of this feature would be to count keypresses from the start of the idle timer, and only restart the idle timer if the threshold is exceeded. I'm sure there are smarter ways to do it, but probably much more cumbersome.

**Comment by algernon** [comment]
These are all reasonable suggestions, and I wholeheartedly agree that the plugin could be smarter. I'm not sure I'll have the time and energy to work on this anytime soon.

For anyone who may want to use this plugin, help is appreciated! It doesn't have to be code, user-stories, describing what you do, or want to do with the plugin is tremendous help in itself.

**Comment by gedankenexperimenter** [comment]
I certainly think this is a low-priority change. I'm sure that people who really want this feature have other ways of implementing it on their computers (and I'm not one of those people, anyway).

I do have one additional thought – if the keyboard has been idle for less than `idle_time_limit` when `lock_time_out` is reached and the keyboard locks the user out, I think the time it remains locked should be `lock_length` minus the previous idle time. If this isn't done, and the user has `lock_length` and `idle_time_limit` both set to five minutes (for example), and the user decides to take a voluntary five-minute break starting four minutes before the `lock_time_out` timer runs out, when he comes back to the keyboard, he ends up having to wait four more minutes before he can type again (or, more likely, he unplugs the keyboard to reset it). Better to avoid that frustration.

**Comment by algernon** [comment]
That's a reasonable suggestion, thanks!

**Comment by gedankenexperimenter** [comment]
If you want to close this issue, go ahead. The changes in #10 didn't implement all of the ideas I began with, but it did get the big one, and anything further involves much bigger changes; I don't intend to address any of it anytime soon.

**Comment by algernon** [comment]
Nah, this should stay open, even if not implemented anytime soon. Serves as a reminder.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#390.
